"""add totp fields to users

Revision ID: ce2dec53098f
Revises: e43601f7d62c
Create Date: 2026-08-19 20:15:51.703324

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce2dec53098f"
down_revision: str | None = "e43601f7d62c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("totp_secret_encrypted", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("totp_confirmed_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "totp_failed_attempts", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column("totp_locked_until", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_locked_until")
    op.drop_column("users", "totp_failed_attempts")
    op.drop_column("users", "totp_confirmed_at")
    op.drop_column("users", "totp_secret_encrypted")
    # ### end Alembic commands ###
