"""add playlists and playlist songs tables

Revision ID: e036811a9272
Revises: 57135bd1015f
Create Date: 2026-09-10 19:07:48.786449

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e036811a9272"
down_revision: str | None = "57135bd1015f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playlists_user_id"), "playlists", ["user_id"], unique=False
    )
    op.create_table(
        "playlist_songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "added_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "playlist_id", "song_id", name="uq_playlist_songs_playlist_id_song_id"
        ),
    )
    op.create_index(
        "ix_playlist_songs_playlist_id_position",
        "playlist_songs",
        ["playlist_id", "position"],
        unique=False,
    )
    op.create_index(
        "ix_playlist_songs_song_id", "playlist_songs", ["song_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_playlist_songs_song_id", table_name="playlist_songs")
    op.drop_index("ix_playlist_songs_playlist_id_position", table_name="playlist_songs")
    op.drop_table("playlist_songs")
    op.drop_index(op.f("ix_playlists_user_id"), table_name="playlists")
    op.drop_table("playlists")
    # ### end Alembic commands ###
