"""add is_premium to users

Revision ID: e43601f7d62c
Revises: f6da57aa9fd8
Create Date: 2026-08-19 19:47:42.338609

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e43601f7d62c"
down_revision: str | None = "f6da57aa9fd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_premium", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_premium")
    # ### end Alembic commands ###
